// Full bilingual translation dictionary. All user-facing strings live here.

export const t = {
  ar: {
    appName: 'نظام تسجيل الأصناف قريبة الانتهاء',
    appTagline: 'Roshen KSA × Relia Distribution',

    selectRole: 'اختر دورك',
    salesman: 'مندوب المبيعات',
    tradeMarketing: 'التريد ماركتنج',
    roshenManager: 'مدير المنطقة روشن',
    password: 'كلمة المرور',
    enterPassword: 'أدخل كلمة المرور',
    login: 'دخول',
    wrongPassword: 'كلمة المرور غير صحيحة',
    logout: 'تسجيل خروج',
    back: 'رجوع',
    next: 'التالي',
    cancel: 'إلغاء',
    save: 'حفظ',
    submit: 'إرسال',
    saved: 'تم الحفظ',
    confirm: 'تأكيد',
    edit: 'تعديل',
    yes: 'نعم',
    no: 'لا',

    // Salesman name selection
    selectYourName: 'اختر اسمك',
    searchByName: 'ابحث بالاسم...',
    noSalesmen: 'لا يوجد بيانات. مدير المنطقة لم يرفع ملف الإكسل بعد.',

    // Customer selection
    selectCustomer: 'اختر العميل',
    searchCustomer: 'ابحث باسم العميل أو الكود...',
    noCustomers: 'لا يوجد عملاء لهذا المندوب.',

    // Item selection
    selectItem: 'اختر الصنف',
    searchItem: 'ابحث باسم أو كود الصنف...',
    noItems: 'لا يوجد أصناف لهذا العميل.',
    netQty: 'الكمية الصافية',
    cases: 'كرتونة',

    // Submission form
    enterDetails: 'أدخل البيانات',
    physicalQty: 'الكمية الفعلية في المحل',
    systemQty: 'الكمية في السيستم',
    expiryDate: 'تاريخ الانتهاء',
    daysRemaining: 'الأيام المتبقية للانتهاء',
    daysExpired: 'منتهي منذ',
    daysAr: 'يوم',
    expiryPhoto: 'صورة تاريخ الانتهاء',
    qtyPhoto: 'صورة الكمية الإجمالية',
    takePhoto: 'التقاط صورة',
    retake: 'إعادة التقاط',
    photoRequired: 'الصورة مطلوبة',
    suggestedAction: 'الإجراء المقترح',
    salesmanSuggestion: 'اقتراح المندوب (للاسترشاد فقط)',
    advisoryOnly: 'استرشادي فقط',
    salesmanNotes: 'ملاحظات المندوب (اختياري)',
    notesPlaceholder: 'مثال: العميل ودود ومستعد للتعاون',
    fillAllFields: 'يرجى إكمال جميع الحقول والصور',
    submissionSent: 'تم إرسال الطلب بنجاح',
    registerAnother: 'تسجيل صنف آخر',
    backToHome: 'العودة للرئيسية',

    // My submissions tracker
    home: 'الرئيسية',
    registerItem: 'تسجيل صنف',
    mySubmissions: 'طلباتي',
    underReview: 'قيد المراجعة',
    approved: 'تمت الموافقة',
    closed: 'مقفول',
    noSubmissions: 'لا توجد طلبات',
    submittedAt: 'تاريخ الإرسال',
    lastUpdate: 'آخر تحديث',
    yourSuggestion: 'اقتراحك',
    tmDecision: 'قرار التريد ماركتنج',
    roshenFinalDecision: 'القرار النهائي للمدير',
    awaitingTM: 'بانتظار التريد ماركتنج',
    awaitingRoshen: 'بانتظار مدير المنطقة',
    closedAtTM: 'مقفول عند التريد ماركتنج',
    decisionEdited: 'تم تعديل القرار',

    // Status labels
    statusPending: 'قيد المراجعة',
    statusWithTM: 'عند التريد ماركتنج',
    statusWithRoshen: 'عند مدير روشن',
    statusApproved: 'تمت الموافقة',
    statusClosed: 'مقفول',
    statusEdited: 'تم التعديل',

    // TM dashboard
    tmDashboard: 'لوحة التريد ماركتنج',
    pendingNew: 'جديد',
    history: 'السجل',
    settings: 'الإعدادات',
    salesmanSuggests: 'اقتراح المندوب',
    pickAction: 'اختر الإجراء',
    tmNotes: 'ملاحظات (اختياري)',
    tmNotesPlaceholder: 'ملاحظات للمدير... (200 حرف كحد أقصى)',
    chooseActionFirst: 'يرجى اختيار إجراء',
    decisionSaved: 'تم حفظ القرار',
    closedRequest: 'تم إقفال الطلب',
    forwardedToRoshen: 'تم إرسال الطلب لمدير المنطقة',

    // Roshen Manager dashboard
    rmDashboard: 'لوحة مدير المنطقة',
    uploadData: 'رفع داتا',
    awaitingMyDecision: 'تنتظر قراري',
    myDecisions: 'قراراتي',
    uploadExcel: 'رفع ملف الإكسل',
    uploadExcelHint: 'ملف Excel يحتوي على Sales Man, Cust Account, Cust Name, Item Id, Item Description, Inv Qty Cases',
    chooseFile: 'اختر ملف',
    uploading: 'جاري الرفع...',
    uploadSuccess: 'تم رفع البيانات بنجاح',
    salesmenCount: 'مندوب',
    customersCount: 'عميل',
    itemsCount: 'صنف',
    rmRecommended: 'توصية التريد ماركتنج',
    yourFinalDecision: 'قرارك النهائي',
    finalDecisionPrompt: 'اختر الإجراء النهائي (الافتراضي = توصية التريد ماركتنج)',
    rmNotes: 'ملاحظاتك (ستظهر في الإيميل)',
    rmNotesPlaceholder: 'اكتب ملاحظاتك...',
    approveAndSend: 'اعتماد وإرسال إيميل',
    emailSent: 'تم إرسال الإيميل بنجاح',
    emailFailed: 'فشل إرسال الإيميل',
    sendingEmail: 'جاري إرسال الإيميل...',

    // Edit window
    editableFor48h: 'قابل للتعديل خلال 48 ساعة',
    editableHoursLeft: 'قابل للتعديل: {h} ساعة متبقية',
    editLocked: '🔒 انتهت فترة التعديل',
    editDecision: 'تعديل القرار',
    decisionUpdated: 'تم تعديل القرار',
    editHistory: 'سجل التعديلات',

    // Photo viewer
    viewBothPhotos: 'عرض الصورتين',
    closePhoto: 'إغلاق',

    // Settings
    emailJSSettings: 'إعدادات الإيميل',
    publicKey: 'EmailJS Public Key',
    serviceId: 'Service ID',
    templateId: 'Template ID',
    rmEmailField: 'إيميل مدير المنطقة (من)',
    tmEmailField: 'إيميل التريد ماركتنج (إلى)',
    configSaved: 'تم حفظ الإعدادات',
    configIncomplete: 'الإعدادات غير مكتملة — يرجى ضبط الإعدادات أولاً',

    // Confirmations
    confirmLogout: 'هل تريد تسجيل الخروج؟',
    confirmSubmit: 'هل تريد إرسال هذا الطلب؟',
    confirmCloseNoAction: 'سيتم إقفال الطلب نهائياً بدون إرسال للمدير. متأكد؟',
    confirmFinalDecision: 'سيتم إرسال إيميل القرار النهائي. متأكد؟',
    confirmEditDecision: 'سيتم تعديل القرار وإرسال إيميل جديد. متأكد؟',

    // Auth
    email: 'البريد الإلكتروني',
    emailPlaceholder: 'name@example.com',
    signIn: 'تسجيل الدخول',
    signingIn: 'جاري الدخول...',
    forgotPassword: 'نسيت كلمة المرور؟',
    forgotPasswordSent: 'تم إرسال رابط إعادة التعيين',
    invalidCredentials: 'بيانات الدخول غير صحيحة',
    noProfile: 'حسابك غير مفعّل. تواصل مع المدير.',
    inactiveAccount: 'الحساب موقوف. تواصل مع المدير.',
    salesmanNameNotInData: 'اسم المندوب غير موجود في بيانات الإكسل بعد. اطلب من المدير رفع بيانات محدثة.',

    // User management
    users: 'المستخدمون',
    userManagement: 'إدارة المستخدمين',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل المستخدم',
    resetPassword: 'إعادة تعيين كلمة المرور',
    newPassword: 'كلمة مرور جديدة',
    generatePassword: 'توليد كلمة مرور',
    deactivate: 'إيقاف',
    activate: 'تفعيل',
    deleteUser: 'حذف نهائي',
    role: 'الدور',
    fullName: 'الاسم الكامل',
    active: 'مفعّل',
    inactive: 'موقوف',
    confirmDeactivate: 'إيقاف هذا المستخدم؟ سيمنع من تسجيل الدخول.',
    confirmDelete: 'حذف نهائي للمستخدم؟ هذا الإجراء لا يمكن التراجع عنه.',
    userCreated: 'تم إنشاء المستخدم',
    userUpdated: 'تم تحديث المستخدم',
    userDeleted: 'تم حذف المستخدم',
    passwordReset: 'تم تغيير كلمة المرور',
    salesmanNameLink: 'اسم المندوب في الإكسل',
    salesmanNameHint: 'يجب أن يطابق اسماً موجوداً في بيانات الإكسل المرفوعة',
    pickFromExcel: 'اختر من الإكسل',
    typeManually: 'اكتب يدوياً',
    noUsers: 'لا يوجد مستخدمون',
    salesmenLabel: 'مندوبون',
    tmLabel: 'تريد ماركتنج',
    rmLabel: 'مدير المنطقة',

    // PDF report
    downloadPdf: 'تحميل PDF',
    generatingPdf: 'جاري إنشاء الملف...',
    pdfReady: 'تم إنشاء الملف',
    pdfFailed: 'فشل إنشاء الملف',
    reportTitle: 'تقرير صنف قريب الانتهاء',
    reportSubtitle: 'Roshen KSA × Relia Distribution',
    sectionSalesman: 'بيانات المندوب',
    sectionCustomer: 'بيانات العميل',
    sectionItem: 'تفاصيل الصنف',
    sectionSalesmanSuggestion: 'اقتراح المندوب (استرشادي)',
    sectionTmDecision: 'قرار التريد ماركتنج',
    sectionRmDecision: 'القرار النهائي لمدير المنطقة',
    sectionPhotos: 'الصور',
    reportGeneratedFrom: 'تم إنشاء هذا التقرير من نظام تسجيل الأصناف قريبة الانتهاء',
    reportPage: 'صفحة {n} من {t}',
    reportSubmissionId: 'رقم الطلب',
    reportGeneratedAt: 'تاريخ إنشاء التقرير',
    reportStatusApproved: 'الحالة: معتمد',
    reportStatusPendingTM: 'الحالة: قيد مراجعة التريد ماركتنج',
    reportStatusPendingRM: 'الحالة: قيد قرار مدير المنطقة',
    reportStatusClosed: 'الحالة: مقفول',
    reportNoDecision: 'لم يصدر قرار بعد',
    approveOnly: 'اعتماد القرار',
    confirmApprove: 'سيتم اعتماد القرار النهائي. متأكد؟',
    confirmEditApprove: 'سيتم تحديث القرار. متأكد؟',
    decisionSavedFinal: 'تم اعتماد القرار',

    // ── Visit-based architecture ──
    startVisit: 'بدء زيارة',
    newVisit: 'زيارة جديدة',
    visit: 'الزيارة',
    visits: 'الزيارات',
    myVisits: 'زياراتي',
    visitId: 'رقم الزيارة',
    visitDate: 'تاريخ الزيارة',
    visitNotes: 'ملاحظات الزيارة (اختياري)',
    visitDraft: 'مسودة',
    visitPendingTm: 'بانتظار التريد ماركتنج',
    visitPendingRm: 'بانتظار مدير المنطقة',
    visitCompleted: 'مكتملة',
    drafts: 'المسودات',
    pending: 'قيد المعالجة',
    completed: 'مكتمل',
    items: 'الأصناف',
    itemsCountLabel: '{n} صنف',
    itemAdd: 'إضافة صنف',
    itemAddNew: 'أضف صنف جديد',
    noItemsYet: 'لم تتم إضافة أصناف بعد. اضغط + للإضافة',
    saveItem: 'حفظ الصنف',
    deleteItem: 'حذف الصنف',
    confirmDeleteItem: 'حذف هذا الصنف؟',
    confirmDeleteVisit: 'حذف هذه المسودة؟',
    deleteVisit: 'حذف الزيارة',
    submitVisit: 'إرسال الزيارة',
    confirmSubmitVisit: 'إرسال هذه الزيارة بعدد {n} صنف؟',
    visitSubmitted: 'تم إرسال الزيارة',
    resumeDraft: 'متابعة المسودة',
    cannotSubmitEmpty: 'أضف على الأقل صنف واحد قبل الإرسال',
    saveAllDecisions: 'حفظ جميع القرارات',
    decisionPerItem: 'القرار لكل صنف',
    decisionsBatchSaved: 'تم حفظ القرارات',
    noDecisionsToSave: 'لا توجد قرارات للحفظ',
    itemPending: 'قيد المراجعة',
    itemApproved: 'معتمد',
    itemClosed: 'مقفول',
    pickCustomer: 'اختر العميل',
    backToVisit: 'العودة للزيارة',
    visitsListEmpty: 'لا توجد زيارات',
    noPhotosYet: 'لم يتم رفع الصور بعد',
    addItemHint: 'أدخل البيانات والصور، ثم احفظ الصنف',

    // ── Email feature ──
    emailLabel: 'إيميل',
    emailSubject: 'موضوع الإيميل',
    emailBody: 'نص الإيميل',
    copySubject: 'نسخ الموضوع',
    copyBody: 'نسخ نص الإيميل',
    copied: '✅ تم النسخ إلى الحافظة',
    emailInstructions: 'انسخ الموضوع والمحتوى ثم الصقهما في Outlook أو Gmail. سيظهر الجدول بتنسيقه الكامل.',
    emailPreparing: 'جاري تحضير الإيميل...',

    // ── Login user-picker ──
    modeSelectFromList: 'اختر من القائمة',
    modeTypeManually: 'اكتب الإيميل يدوياً',
    pickYourName: 'اختر اسمك',
    pickedAs: 'سجل الدخول كـ',
    loadingUsers: 'جاري تحميل قائمة المستخدمين...',
    noUserFound: 'لا يوجد مستخدم بهذا الاسم',
    userListUnavailable: 'قائمة المستخدمين غير متاحة، يرجى كتابة الإيميل يدوياً',
    changeUser: 'تغيير المستخدم',
  },

  en: {
    appName: 'Near Expiry Registration System',
    appTagline: 'Roshen KSA × Relia Distribution',

    selectRole: 'Select your role',
    salesman: 'Salesman',
    tradeMarketing: 'Trade Marketing',
    roshenManager: 'Roshen Area Manager',
    password: 'Password',
    enterPassword: 'Enter password',
    login: 'Login',
    wrongPassword: 'Wrong password',
    logout: 'Logout',
    back: 'Back',
    next: 'Next',
    cancel: 'Cancel',
    save: 'Save',
    submit: 'Submit',
    saved: 'Saved',
    confirm: 'Confirm',
    edit: 'Edit',
    yes: 'Yes',
    no: 'No',

    selectYourName: 'Select your name',
    searchByName: 'Search by name...',
    noSalesmen: 'No data yet. The Roshen Manager has not uploaded the Excel file.',

    selectCustomer: 'Select customer',
    searchCustomer: 'Search by customer name or code...',
    noCustomers: 'No customers for this salesman.',

    selectItem: 'Select item',
    searchItem: 'Search by item name or code...',
    noItems: 'No items for this customer.',
    netQty: 'Net qty',
    cases: 'cases',

    enterDetails: 'Enter details',
    physicalQty: 'Physical qty in shop',
    systemQty: 'System qty',
    expiryDate: 'Expiry date',
    daysRemaining: 'Days remaining',
    daysExpired: 'Expired since',
    daysAr: 'days',
    expiryPhoto: 'Expiry date photo',
    qtyPhoto: 'Total stock photo',
    takePhoto: 'Take photo',
    retake: 'Retake',
    photoRequired: 'Photo required',
    suggestedAction: 'Suggested action',
    salesmanSuggestion: "Salesman's suggestion (advisory only)",
    advisoryOnly: 'Advisory only',
    salesmanNotes: "Salesman's notes (optional)",
    notesPlaceholder: 'e.g., Customer is friendly and willing to cooperate',
    fillAllFields: 'Please fill all fields and both photos',
    submissionSent: 'Submission sent successfully',
    registerAnother: 'Register another item',
    backToHome: 'Back to home',

    home: 'Home',
    registerItem: 'Register item',
    mySubmissions: 'My submissions',
    underReview: 'Under review',
    approved: 'Approved',
    closed: 'Closed',
    noSubmissions: 'No submissions',
    submittedAt: 'Submitted',
    lastUpdate: 'Last update',
    yourSuggestion: 'Your suggestion',
    tmDecision: 'Trade Marketing decision',
    roshenFinalDecision: "Manager's final decision",
    awaitingTM: 'With Trade Marketing',
    awaitingRoshen: 'With Roshen Manager',
    closedAtTM: 'Closed at Trade Marketing',
    decisionEdited: 'Decision edited',

    statusPending: 'Under review',
    statusWithTM: 'With Trade Marketing',
    statusWithRoshen: 'With Roshen Manager',
    statusApproved: 'Approved',
    statusClosed: 'Closed',
    statusEdited: 'Edited',

    tmDashboard: 'Trade Marketing',
    pendingNew: 'New',
    history: 'History',
    settings: 'Settings',
    salesmanSuggests: 'Salesman suggests',
    pickAction: 'Pick action',
    tmNotes: 'Notes (optional)',
    tmNotesPlaceholder: 'Notes for the manager... (max 200 chars)',
    chooseActionFirst: 'Please choose an action',
    decisionSaved: 'Decision saved',
    closedRequest: 'Request closed',
    forwardedToRoshen: 'Forwarded to Roshen Manager',

    rmDashboard: 'Roshen Manager',
    uploadData: 'Upload data',
    awaitingMyDecision: 'Awaiting my decision',
    myDecisions: 'My decisions',
    uploadExcel: 'Upload Excel file',
    uploadExcelHint: 'Excel file with Sales Man, Cust Account, Cust Name, Item Id, Item Description, Inv Qty Cases',
    chooseFile: 'Choose file',
    uploading: 'Uploading...',
    uploadSuccess: 'Data uploaded successfully',
    salesmenCount: 'salesmen',
    customersCount: 'customers',
    itemsCount: 'items',
    rmRecommended: 'TM recommendation',
    yourFinalDecision: 'Your final decision',
    finalDecisionPrompt: 'Choose final action (default = TM recommendation)',
    rmNotes: 'Your notes (will appear in email)',
    rmNotesPlaceholder: 'Write your notes...',
    approveAndSend: 'Approve & send email',
    emailSent: 'Email sent successfully',
    emailFailed: 'Email failed to send',
    sendingEmail: 'Sending email...',

    editableFor48h: 'Editable within 48 hours',
    editableHoursLeft: 'Editable: {h}h remaining',
    editLocked: '🔒 Edit window closed',
    editDecision: 'Edit decision',
    decisionUpdated: 'Decision updated',
    editHistory: 'Edit history',

    viewBothPhotos: 'View both photos',
    closePhoto: 'Close',

    emailJSSettings: 'EmailJS settings',
    publicKey: 'EmailJS Public Key',
    serviceId: 'Service ID',
    templateId: 'Template ID',
    rmEmailField: 'Roshen Manager email (from)',
    tmEmailField: 'Trade Marketing email (to)',
    configSaved: 'Settings saved',
    configIncomplete: 'Email settings incomplete — please configure first',

    confirmLogout: 'Logout?',
    confirmSubmit: 'Submit this request?',
    confirmCloseNoAction: 'This will close the request permanently without forwarding. Continue?',
    confirmFinalDecision: 'Final decision email will be sent. Continue?',
    confirmEditDecision: 'Decision will be updated and a new email sent. Continue?',

    email: 'Email',
    emailPlaceholder: 'name@example.com',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    forgotPassword: 'Forgot password?',
    forgotPasswordSent: 'Reset link sent',
    invalidCredentials: 'Invalid credentials',
    noProfile: 'Your account is not provisioned. Contact your manager.',
    inactiveAccount: 'Account is deactivated. Contact your manager.',
    salesmanNameNotInData: "Your salesman name isn't in the latest Excel yet. Ask the manager to upload fresh data.",

    users: 'Users',
    userManagement: 'User management',
    addUser: 'Add user',
    editUser: 'Edit user',
    resetPassword: 'Reset password',
    newPassword: 'New password',
    generatePassword: 'Generate password',
    deactivate: 'Deactivate',
    activate: 'Activate',
    deleteUser: 'Delete user',
    role: 'Role',
    fullName: 'Full name',
    active: 'Active',
    inactive: 'Inactive',
    confirmDeactivate: 'Deactivate this user? They will be locked out of the app.',
    confirmDelete: 'Permanently delete this user? This cannot be undone.',
    userCreated: 'User created',
    userUpdated: 'User updated',
    userDeleted: 'User deleted',
    passwordReset: 'Password updated',
    salesmanNameLink: 'Salesman name (in Excel)',
    salesmanNameHint: 'Must match a name present in the uploaded Excel data',
    pickFromExcel: 'Pick from Excel',
    typeManually: 'Type manually',
    noUsers: 'No users yet',
    salesmenLabel: 'Salesmen',
    tmLabel: 'Trade Marketing',
    rmLabel: 'Roshen Manager',

    downloadPdf: 'Download PDF',
    generatingPdf: 'Generating PDF…',
    pdfReady: 'PDF ready',
    pdfFailed: 'PDF generation failed',
    reportTitle: 'Near Expiry Registration Report',
    reportSubtitle: 'Roshen KSA × Relia Distribution',
    sectionSalesman: 'Salesman info',
    sectionCustomer: 'Customer info',
    sectionItem: 'Item details',
    sectionSalesmanSuggestion: 'Salesman suggestion (advisory)',
    sectionTmDecision: 'Trade Marketing decision',
    sectionRmDecision: 'Roshen Manager final decision',
    sectionPhotos: 'Photos',
    reportGeneratedFrom: 'Generated from Near Expiry Registration System',
    reportPage: 'Page {n} of {t}',
    reportSubmissionId: 'Submission ID',
    reportGeneratedAt: 'Generated at',
    reportStatusApproved: 'STATUS: APPROVED',
    reportStatusPendingTM: 'STATUS: With Trade Marketing',
    reportStatusPendingRM: 'STATUS: With Roshen Manager',
    reportStatusClosed: 'STATUS: Closed',
    reportNoDecision: 'No decision yet',
    approveOnly: 'Approve',
    confirmApprove: 'Approve this as the final decision?',
    confirmEditApprove: 'Update the decision?',
    decisionSavedFinal: 'Decision approved',

    startVisit: 'Start visit',
    newVisit: 'New visit',
    visit: 'Visit',
    visits: 'Visits',
    myVisits: 'My visits',
    visitId: 'Visit ID',
    visitDate: 'Visit date',
    visitNotes: 'Visit notes (optional)',
    visitDraft: 'Draft',
    visitPendingTm: 'With Trade Marketing',
    visitPendingRm: 'With Roshen Manager',
    visitCompleted: 'Completed',
    drafts: 'Drafts',
    pending: 'Pending',
    completed: 'Completed',
    items: 'Items',
    itemsCountLabel: '{n} item(s)',
    itemAdd: 'Add item',
    itemAddNew: 'Add a new item',
    noItemsYet: 'No items added yet. Tap + to add.',
    saveItem: 'Save item',
    deleteItem: 'Delete item',
    confirmDeleteItem: 'Delete this item?',
    confirmDeleteVisit: 'Delete this draft?',
    deleteVisit: 'Delete visit',
    submitVisit: 'Submit visit',
    confirmSubmitVisit: 'Submit this visit with {n} item(s)?',
    visitSubmitted: 'Visit submitted',
    resumeDraft: 'Resume draft',
    cannotSubmitEmpty: 'Add at least one item before submitting',
    saveAllDecisions: 'Save all decisions',
    decisionPerItem: 'Per-item decision',
    decisionsBatchSaved: 'Decisions saved',
    noDecisionsToSave: 'No decisions to save',
    itemPending: 'Pending',
    itemApproved: 'Approved',
    itemClosed: 'Closed',
    pickCustomer: 'Pick a customer',
    backToVisit: 'Back to visit',
    visitsListEmpty: 'No visits',
    noPhotosYet: 'No photos uploaded yet',
    addItemHint: 'Fill in the details and photos, then save the item',

    emailLabel: 'Email',
    emailSubject: 'Email subject',
    emailBody: 'Email body',
    copySubject: 'Copy subject',
    copyBody: 'Copy email body',
    copied: '✅ Copied to clipboard',
    emailInstructions: 'Copy the subject and body, then paste into Outlook or Gmail. The table will render with full formatting.',
    emailPreparing: 'Preparing email…',

    modeSelectFromList: 'Select from list',
    modeTypeManually: 'Type manually',
    pickYourName: 'Pick your name',
    pickedAs: 'Signing in as',
    loadingUsers: 'Loading users…',
    noUserFound: 'No user found',
    userListUnavailable: 'User list unavailable — please type your email manually',
    changeUser: 'Change user',
  },
};

import { getLangPref, setLangPref } from './storage.js';

export const getLang = () => getLangPref();

export const setLang = (lang) => {
  setLangPref(lang);
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  document.documentElement.lang = lang;
};
