// Full bilingual translation dictionary. All user-facing strings live here.

export const t = {
  ar: {
    appName: 'نظام تسجيل الأصناف قريبة الانتهاء',
    appTagline: 'Roshen KSA × Relia Distribution',

    selectRole: 'اختر دورك',
    salesman: 'مندوب المبيعات',
    tradeMarketing: 'التريد ماركتنج',
    roshenManager: 'مدير المنطقة روشن',
    password: 'كلمة المرور',
    enterPassword: 'أدخل كلمة المرور',
    login: 'دخول',
    wrongPassword: 'كلمة المرور غير صحيحة',
    logout: 'تسجيل خروج',
    back: 'رجوع',
    next: 'التالي',
    cancel: 'إلغاء',
    save: 'حفظ',
    submit: 'إرسال',
    saved: 'تم الحفظ',
    confirm: 'تأكيد',
    edit: 'تعديل',
    yes: 'نعم',
    no: 'لا',

    // Salesman name selection
    selectYourName: 'اختر اسمك',
    searchByName: 'ابحث بالاسم...',
    noSalesmen: 'لا يوجد بيانات. مدير المنطقة لم يرفع ملف الإكسل بعد.',

    // Customer selection
    selectCustomer: 'اختر العميل',
    searchCustomer: 'ابحث باسم العميل أو الكود...',
    noCustomers: 'لا يوجد عملاء لهذا المندوب.',

    // Item selection
    selectItem: 'اختر الصنف',
    searchItem: 'ابحث باسم أو كود الصنف...',
    noItems: 'لا يوجد أصناف لهذا العميل.',
    netQty: 'الكمية الصافية',
    cases: 'كرتونة',

    // Submission form
    enterDetails: 'أدخل البيانات',
    physicalQty: 'الكمية الفعلية في المحل',
    systemQty: 'الكمية في السيستم',
    expiryDate: 'تاريخ الانتهاء',
    daysRemaining: 'الأيام المتبقية للانتهاء',
    daysExpired: 'منتهي منذ',
    daysAr: 'يوم',
    expiryPhoto: 'صورة تاريخ الانتهاء',
    qtyPhoto: 'صورة الكمية الإجمالية',
    takePhoto: 'التقاط صورة',
    retake: 'إعادة التقاط',
    photoRequired: 'الصورة مطلوبة',
    suggestedAction: 'الإجراء المقترح',
    salesmanSuggestion: 'اقتراح المندوب (للاسترشاد فقط)',
    advisoryOnly: 'استرشادي فقط',
    salesmanNotes: 'ملاحظات المندوب (اختياري)',
    notesPlaceholder: 'مثال: العميل ودود ومستعد للتعاون',
    fillAllFields: 'يرجى إكمال جميع الحقول والصور',
    submissionSent: 'تم إرسال الطلب بنجاح',
    registerAnother: 'تسجيل صنف آخر',
    backToHome: 'العودة للرئيسية',

    // My submissions tracker
    home: 'الرئيسية',
    registerItem: 'تسجيل صنف',
    mySubmissions: 'طلباتي',
    underReview: 'قيد المراجعة',
    approved: 'تمت الموافقة',
    closed: 'مقفول',
    noSubmissions: 'لا توجد طلبات',
    submittedAt: 'تاريخ الإرسال',
    lastUpdate: 'آخر تحديث',
    yourSuggestion: 'اقتراحك',
    tmDecision: 'قرار التريد ماركتنج',
    roshenFinalDecision: 'القرار النهائي للمدير',
    awaitingTM: 'بانتظار التريد ماركتنج',
    awaitingRoshen: 'بانتظار مدير المنطقة',
    closedAtTM: 'مقفول عند التريد ماركتنج',
    decisionEdited: 'تم تعديل القرار',

    // Status labels
    statusPending: 'قيد المراجعة',
    statusWithTM: 'عند التريد ماركتنج',
    statusWithRoshen: 'عند مدير روشن',
    statusApproved: 'تمت الموافقة',
    statusClosed: 'مقفول',
    statusEdited: 'تم التعديل',

    // TM dashboard
    tmDashboard: 'لوحة التريد ماركتنج',
    pendingNew: 'جديد',
    history: 'السجل',
    settings: 'الإعدادات',
    salesmanSuggests: 'اقتراح المندوب',
    pickAction: 'اختر الإجراء',
    tmNotes: 'ملاحظات (اختياري)',
    tmNotesPlaceholder: 'ملاحظات للمدير... (200 حرف كحد أقصى)',
    chooseActionFirst: 'يرجى اختيار إجراء',
    decisionSaved: 'تم حفظ القرار',
    closedRequest: 'تم إقفال الطلب',
    forwardedToRoshen: 'تم إرسال الطلب لمدير المنطقة',

    // Roshen Manager dashboard
    rmDashboard: 'لوحة مدير المنطقة',
    uploadData: 'رفع داتا',
    awaitingMyDecision: 'تنتظر قراري',
    myDecisions: 'قراراتي',
    uploadExcel: 'رفع ملف الإكسل',
    uploadExcelHint: 'ملف Excel يحتوي على Sales Man, Cust Account, Cust Name, Item Id, Item Description, Inv Qty Cases',
    chooseFile: 'اختر ملف',
    uploading: 'جاري الرفع...',
    uploadSuccess: 'تم رفع البيانات بنجاح',
    salesmenCount: 'مندوب',
    customersCount: 'عميل',
    itemsCount: 'صنف',
    rmRecommended: 'توصية التريد ماركتنج',
    yourFinalDecision: 'قرارك النهائي',
    finalDecisionPrompt: 'اختر الإجراء النهائي (الافتراضي = توصية التريد ماركتنج)',
    rmNotes: 'ملاحظاتك (ستظهر في الإيميل)',
    rmNotesPlaceholder: 'اكتب ملاحظاتك...',
    approveAndSend: 'اعتماد وإرسال إيميل',
    emailSent: 'تم إرسال الإيميل بنجاح',
    emailFailed: 'فشل إرسال الإيميل',
    sendingEmail: 'جاري إرسال الإيميل...',

    // Edit window
    editableFor48h: 'قابل للتعديل خلال 48 ساعة',
    editableHoursLeft: 'قابل للتعديل: {h} ساعة متبقية',
    editLocked: '🔒 انتهت فترة التعديل',
    editDecision: 'تعديل القرار',
    decisionUpdated: 'تم تعديل القرار',
    editHistory: 'سجل التعديلات',

    // Photo viewer
    viewBothPhotos: 'عرض الصورتين',
    closePhoto: 'إغلاق',

    // Settings
    emailJSSettings: 'إعدادات الإيميل',
    publicKey: 'EmailJS Public Key',
    serviceId: 'Service ID',
    templateId: 'Template ID',
    rmEmailField: 'إيميل مدير المنطقة (من)',
    tmEmailField: 'إيميل التريد ماركتنج (إلى)',
    configSaved: 'تم حفظ الإعدادات',
    configIncomplete: 'الإعدادات غير مكتملة — يرجى ضبط الإعدادات أولاً',

    // Confirmations
    confirmLogout: 'هل تريد تسجيل الخروج؟',
    confirmSubmit: 'هل تريد إرسال هذا الطلب؟',
    confirmCloseNoAction: 'سيتم إقفال الطلب نهائياً بدون إرسال للمدير. متأكد؟',
    confirmFinalDecision: 'سيتم إرسال إيميل القرار النهائي. متأكد؟',
    confirmEditDecision: 'سيتم تعديل القرار وإرسال إيميل جديد. متأكد؟',
  },

  en: {
    appName: 'Near Expiry Registration System',
    appTagline: 'Roshen KSA × Relia Distribution',

    selectRole: 'Select your role',
    salesman: 'Salesman',
    tradeMarketing: 'Trade Marketing',
    roshenManager: 'Roshen Area Manager',
    password: 'Password',
    enterPassword: 'Enter password',
    login: 'Login',
    wrongPassword: 'Wrong password',
    logout: 'Logout',
    back: 'Back',
    next: 'Next',
    cancel: 'Cancel',
    save: 'Save',
    submit: 'Submit',
    saved: 'Saved',
    confirm: 'Confirm',
    edit: 'Edit',
    yes: 'Yes',
    no: 'No',

    selectYourName: 'Select your name',
    searchByName: 'Search by name...',
    noSalesmen: 'No data yet. The Roshen Manager has not uploaded the Excel file.',

    selectCustomer: 'Select customer',
    searchCustomer: 'Search by customer name or code...',
    noCustomers: 'No customers for this salesman.',

    selectItem: 'Select item',
    searchItem: 'Search by item name or code...',
    noItems: 'No items for this customer.',
    netQty: 'Net qty',
    cases: 'cases',

    enterDetails: 'Enter details',
    physicalQty: 'Physical qty in shop',
    systemQty: 'System qty',
    expiryDate: 'Expiry date',
    daysRemaining: 'Days remaining',
    daysExpired: 'Expired since',
    daysAr: 'days',
    expiryPhoto: 'Expiry date photo',
    qtyPhoto: 'Total stock photo',
    takePhoto: 'Take photo',
    retake: 'Retake',
    photoRequired: 'Photo required',
    suggestedAction: 'Suggested action',
    salesmanSuggestion: "Salesman's suggestion (advisory only)",
    advisoryOnly: 'Advisory only',
    salesmanNotes: "Salesman's notes (optional)",
    notesPlaceholder: 'e.g., Customer is friendly and willing to cooperate',
    fillAllFields: 'Please fill all fields and both photos',
    submissionSent: 'Submission sent successfully',
    registerAnother: 'Register another item',
    backToHome: 'Back to home',

    home: 'Home',
    registerItem: 'Register item',
    mySubmissions: 'My submissions',
    underReview: 'Under review',
    approved: 'Approved',
    closed: 'Closed',
    noSubmissions: 'No submissions',
    submittedAt: 'Submitted',
    lastUpdate: 'Last update',
    yourSuggestion: 'Your suggestion',
    tmDecision: 'Trade Marketing decision',
    roshenFinalDecision: "Manager's final decision",
    awaitingTM: 'With Trade Marketing',
    awaitingRoshen: 'With Roshen Manager',
    closedAtTM: 'Closed at Trade Marketing',
    decisionEdited: 'Decision edited',

    statusPending: 'Under review',
    statusWithTM: 'With Trade Marketing',
    statusWithRoshen: 'With Roshen Manager',
    statusApproved: 'Approved',
    statusClosed: 'Closed',
    statusEdited: 'Edited',

    tmDashboard: 'Trade Marketing',
    pendingNew: 'New',
    history: 'History',
    settings: 'Settings',
    salesmanSuggests: 'Salesman suggests',
    pickAction: 'Pick action',
    tmNotes: 'Notes (optional)',
    tmNotesPlaceholder: 'Notes for the manager... (max 200 chars)',
    chooseActionFirst: 'Please choose an action',
    decisionSaved: 'Decision saved',
    closedRequest: 'Request closed',
    forwardedToRoshen: 'Forwarded to Roshen Manager',

    rmDashboard: 'Roshen Manager',
    uploadData: 'Upload data',
    awaitingMyDecision: 'Awaiting my decision',
    myDecisions: 'My decisions',
    uploadExcel: 'Upload Excel file',
    uploadExcelHint: 'Excel file with Sales Man, Cust Account, Cust Name, Item Id, Item Description, Inv Qty Cases',
    chooseFile: 'Choose file',
    uploading: 'Uploading...',
    uploadSuccess: 'Data uploaded successfully',
    salesmenCount: 'salesmen',
    customersCount: 'customers',
    itemsCount: 'items',
    rmRecommended: 'TM recommendation',
    yourFinalDecision: 'Your final decision',
    finalDecisionPrompt: 'Choose final action (default = TM recommendation)',
    rmNotes: 'Your notes (will appear in email)',
    rmNotesPlaceholder: 'Write your notes...',
    approveAndSend: 'Approve & send email',
    emailSent: 'Email sent successfully',
    emailFailed: 'Email failed to send',
    sendingEmail: 'Sending email...',

    editableFor48h: 'Editable within 48 hours',
    editableHoursLeft: 'Editable: {h}h remaining',
    editLocked: '🔒 Edit window closed',
    editDecision: 'Edit decision',
    decisionUpdated: 'Decision updated',
    editHistory: 'Edit history',

    viewBothPhotos: 'View both photos',
    closePhoto: 'Close',

    emailJSSettings: 'EmailJS settings',
    publicKey: 'EmailJS Public Key',
    serviceId: 'Service ID',
    templateId: 'Template ID',
    rmEmailField: 'Roshen Manager email (from)',
    tmEmailField: 'Trade Marketing email (to)',
    configSaved: 'Settings saved',
    configIncomplete: 'Email settings incomplete — please configure first',

    confirmLogout: 'Logout?',
    confirmSubmit: 'Submit this request?',
    confirmCloseNoAction: 'This will close the request permanently without forwarding. Continue?',
    confirmFinalDecision: 'Final decision email will be sent. Continue?',
    confirmEditDecision: 'Decision will be updated and a new email sent. Continue?',
  },
};

export const getLang = () => {
  try {
    return localStorage.getItem('nex_lang') || 'ar';
  } catch {
    return 'ar';
  }
};

export const setLang = (lang) => {
  try {
    localStorage.setItem('nex_lang', lang);
  } catch {}
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  document.documentElement.lang = lang;
};
