-- ============================================================================
-- Trade Spend Native Module — Migration 004 (RESOLUTION TEMPLATE)
-- Target Supabase project: "Roshen" (ref wrkugzssuoxneftzappa)
-- Purpose: populate dash_sku_master.category for the CONFLICT items — those seen
--          with MORE THAN ONE category historically. These MUST be confirmed by
--          a human (see the Conflict Report). Nothing here runs automatically.
--
-- STATUS: TEMPLATE — DO NOT APPLY AS-IS.
-- Each line's category is the FREQUENCY-MAJORITY SUGGESTION only. Review, edit,
-- and approve, then apply. The one genuine tie (Fudgenta) has NO suggestion.
--
-- Format: <category>  -- <observed categories with activity counts>
-- ============================================================================

-- update public.dash_sku_master set category = 'Bonny Fruit'
--  where lower(description) = lower('Roshen Bonny Fruit Berry Mix, Mixed Fruit Flavoured Jelly 18 X 200G');   -- Bonny Fruit 34 | Sweet Packet 3 | Johnny Krocker 350 G 2
-- update public.dash_sku_master set category = 'Bonny Fruit'
--  where lower(description) = lower('Roshen Bonny Fruit Citrus Mix, Mixed Fruit Flavoured Jelly 18 X 200G');  -- Bonny Fruit 34 | Sweet Packet 3 | Johnny Krocker 350 G 2
-- update public.dash_sku_master set category = 'Bonny Fruit'
--  where lower(description) = lower('Roshen Bonny Fruit Summer Mix, Mixed Fruit Flavoured Jelly 18 X 200G');  -- Bonny Fruit 34 | Sweet Packet 3 | Johnny Krocker 350 G 2
-- update public.dash_sku_master set category = '2 Crack'
--  where lower(description) = lower('Roshen Cracker 2 Crack with Cocoa-Hazelnut Filling  26 X 190g');         -- 2 Crack 2 | Sweet Packet 1
-- update public.dash_sku_master set category = '2 Crack'
--  where lower(description) = lower('Roshen Cracker 2 Crack with Milk-Vanila Filling  26 X 190g');            -- 2 Crack 2 | Sweet Packet 1
-- update public.dash_sku_master set category = 'Johnny Krocker 350 G'
--  where lower(description) = lower('Roshen Johnny Krocker Choco Wafer 12X350G');                             -- Johnny Krocker 350 G 7 | Bonny Fruit 2
-- update public.dash_sku_master set category = 'Johnny Krocker 350 G'
--  where lower(description) = lower('Roshen Johnny Krocker Milk Wafer 12X350G');                              -- Johnny Krocker 350 G 7 | Bonny Fruit 2
-- update public.dash_sku_master set category = 'Sweet Packet'
--  where lower(description) = lower('Roshen Hard Candies Bim-Bom 11 X 200G');                                 -- Sweet Packet 9 | Bonny Fruit 3 | 2 Crack 1 | Fudgenta 400 G 1
-- update public.dash_sku_master set category = 'Sweet Packet'
--  where lower(description) = lower('Roshen Hard Candies Sweet Drop 12 X 150G');                              -- Sweet Packet 9 | Bonny Fruit 3 | 2 Crack 1 | Fudgenta 400 G 1
-- update public.dash_sku_master set category = 'Sweet Packet'
--  where lower(description) = lower('Roshen Jelly Candies Сrazy Bee Frutty 12 X 200G');                       -- Sweet Packet 9 | Bonny Fruit 3 | 2 Crack 1 | Fudgenta 400 G 1
-- update public.dash_sku_master set category = 'Sweet Packet'
--  where lower(description) = lower('Roshen Jelly Candy 13X200G');                                            -- Sweet Packet 9 | Bonny Fruit 3 | 2 Crack 1 | Fudgenta 400 G 1
-- update public.dash_sku_master set category = 'Sweet Packet'
--  where lower(description) = lower('Roshen Korivka Milk Sweets 12X205G');                                    -- Sweet Packet 9 | Bonny Fruit 3 | 2 Crack 1 | Fudgenta 400 G 1
-- update public.dash_sku_master set category = 'Sweet Packet'
--  where lower(description) = lower('Roshen Milky Splash Toffee With Milk Filling 12 X 150G');                -- Sweet Packet 9 | Bonny Fruit 3 | 2 Crack 1 | Fudgenta 400 G 1

-- GENUINE TIE — needs an explicit human decision (no majority):
-- update public.dash_sku_master set category = '???'
--  where lower(description) = lower('Roshen Fudgenta 16X400G');                                               -- Fudgenta 400 G 1 | Sweet Packet 1  (1-1 tie)

-- Data-hygiene note: category '2 Crack ' carries a trailing space in the source
-- data; suggestions above trim it. Confirm the canonical spelling when approving.
