import { jsPDF } from 'jspdf'
import { format } from 'date-fns'
import { categoryLabel, visitStatusLabel, visitTypeLabel } from '@/lib/constants'
import { googleMapsUrl } from '@/lib/utils'
import { loadReportImages } from '@/lib/report/images'
import type { ReportCustomerSection, ReportData } from '@/lib/report/build'
import type { VisitStatus } from '@/types'

const RED: [number, number, number] = [227, 6, 19]
const INK: [number, number, number] = [22, 22, 28]
const MUTED: [number, number, number] = [120, 120, 132]
const LINE: [number, number, number] = [226, 226, 232]
const SOFT: [number, number, number] = [248, 248, 250]

const STATUS_RGB: Record<VisitStatus, [number, number, number]> = {
  excellent: [52, 199, 89],
  good: [0, 122, 255],
  needs_follow_up: [255, 149, 0],
  urgent: [227, 6, 19],
}

const MAX_PHOTOS_PER_CUSTOMER = 24

/** Formats a timestamp, tolerating null/undefined/invalid values (→ "—"). */
function safeDate(value: string | null | undefined, fmt: string): string {
  if (!value) return '—'
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return '—'
  try {
    return format(d, fmt)
  } catch {
    return '—'
  }
}

class Report {
  doc: jsPDF
  W: number
  H: number
  M = 40
  y = 40
  images: Record<string, string>

  constructor(images: Record<string, string>) {
    this.doc = new jsPDF({ unit: 'pt', format: 'a4', compress: true })
    this.W = this.doc.internal.pageSize.getWidth()
    this.H = this.doc.internal.pageSize.getHeight()
    this.images = images
  }

  get contentW() {
    return this.W - this.M * 2
  }

  ensure(height: number) {
    if (this.y + height > this.H - 54) this.newPage()
  }

  newPage() {
    this.doc.addPage()
    this.y = this.M
  }

  logo(x: number, y: number, size: number) {
    const d = this.doc
    d.setFillColor(...RED)
    d.roundedRect(x, y, size, size, size * 0.22, size * 0.22, 'F')
    d.setFillColor(255, 255, 255)
    d.circle(x + size / 2, y + size * 0.42, size * 0.2, 'F')
    d.setFillColor(...RED)
    d.circle(x + size / 2, y + size * 0.42, size * 0.09, 'F')
    d.triangle(
      x + size * 0.34, y + size * 0.5,
      x + size * 0.66, y + size * 0.5,
      x + size / 2, y + size * 0.78,
      'F',
    )
    d.setFillColor(255, 255, 255)
  }

  text(str: string, x: number, y: number, opts?: { size?: number; bold?: boolean; color?: [number, number, number]; align?: 'left' | 'center' | 'right' }) {
    this.doc.setFont('helvetica', opts?.bold ? 'bold' : 'normal')
    this.doc.setFontSize(opts?.size ?? 10)
    this.doc.setTextColor(...(opts?.color ?? INK))
    this.doc.text(str, x, y, { align: opts?.align ?? 'left' })
  }

  // ---------------------------------------------------------------- cover

  cover(data: ReportData) {
    const d = this.doc
    d.setFillColor(...RED)
    d.rect(0, 0, this.W, 260, 'F')
    // subtle darker band
    d.setFillColor(180, 5, 15)
    d.rect(0, 220, this.W, 40, 'F')

    this.logo(this.M, 60, 54)
    this.text('Roshen Visit Log', this.M + 70, 84, { size: 22, bold: true, color: [255, 255, 255] })
    this.text('Professional Visit Report', this.M + 70, 106, { size: 12, color: [255, 235, 236] })

    this.text('REPORT PERIOD', this.M, 170, { size: 9, bold: true, color: [255, 210, 212] })
    this.text(data.periodLabel, this.M, 190, { size: 15, bold: true, color: [255, 255, 255] })

    this.text(data.reportId, this.W - this.M, 170, { size: 10, bold: true, color: [255, 235, 236], align: 'right' })
    this.text(
      format(new Date(data.generatedAt), 'd MMM yyyy, HH:mm'),
      this.W - this.M,
      190,
      { size: 10, color: [255, 235, 236], align: 'right' },
    )

    // KPI tiles
    const tiles: [string, string][] = [
      ['Customers', String(data.totals.customers)],
      ['Visits', String(data.totals.visits)],
      ['Photos', String(data.totals.photos)],
      ['GPS Verified', String(data.totals.gpsVerified)],
    ]
    const gap = 12
    const tileW = (this.contentW - gap * 3) / 4
    const tileY = 300
    tiles.forEach((t, i) => {
      const x = this.M + i * (tileW + gap)
      d.setFillColor(...SOFT)
      d.roundedRect(x, tileY, tileW, 72, 10, 10, 'F')
      this.text(t[1], x + tileW / 2, tileY + 38, { size: 22, bold: true, align: 'center' })
      this.text(t[0], x + tileW / 2, tileY + 58, { size: 9, color: MUTED, align: 'center' })
    })

    // Meta block
    let my = 420
    const metaRow = (label: string, value: string) => {
      this.text(label, this.M, my, { size: 10, color: MUTED })
      this.text(value, this.W - this.M, my, { size: 10, bold: true, align: 'right' })
      d.setDrawColor(...LINE)
      d.line(this.M, my + 10, this.W - this.M, my + 10)
      my += 30
    }
    metaRow('Generated By', data.userName)
    metaRow('Generated Date & Time', format(new Date(data.generatedAt), 'd MMMM yyyy, HH:mm'))
    metaRow('Report Period', data.periodLabel)
    metaRow('Report ID', data.reportId)
    metaRow('Total Customers', String(data.totals.customers))
    metaRow('Total Visits', String(data.totals.visits))
    metaRow('Total Photos', String(data.totals.photos))
    metaRow('GPS Verified Visits', String(data.totals.gpsVerified))

    this.text('Roshen · Confidential — for internal sales reporting', this.M, this.H - 40, {
      size: 9,
      color: MUTED,
    })
  }

  // ------------------------------------------------------- executive summary

  sectionTitle(title: string) {
    this.ensure(40)
    this.text(title, this.M, this.y + 6, { size: 15, bold: true })
    this.doc.setDrawColor(...RED)
    this.doc.setLineWidth(2)
    this.doc.line(this.M, this.y + 12, this.M + 46, this.y + 12)
    this.doc.setLineWidth(0.5)
    this.y += 30
  }

  kpiGrid(items: [string, string][]) {
    const perRow = 3
    const gap = 12
    const cardW = (this.contentW - gap * (perRow - 1)) / perRow
    const cardH = 60
    items.forEach((item, i) => {
      const col = i % perRow
      if (col === 0) this.ensure(cardH + gap)
      const x = this.M + col * (cardW + gap)
      const rowY = this.y
      this.doc.setFillColor(...SOFT)
      this.doc.roundedRect(x, rowY, cardW, cardH, 8, 8, 'F')
      this.text(item[1], x + 12, rowY + 30, { size: 18, bold: true })
      this.text(item[0], x + 12, rowY + 47, { size: 9, color: MUTED })
      if (col === perRow - 1 || i === items.length - 1) this.y += cardH + gap
    })
  }

  bars(title: string, entries: [string, number, [number, number, number]?][]) {
    if (entries.length === 0) return
    const total = Math.max(1, entries.reduce((s, e) => s + e[1], 0))
    this.ensure(24 + entries.length * 22)
    this.text(title, this.M, this.y + 4, { size: 11, bold: true })
    this.y += 16
    for (const [label, value, color] of entries) {
      this.ensure(22)
      this.text(label, this.M, this.y + 9, { size: 9 })
      this.text(String(value), this.W - this.M, this.y + 9, { size: 9, bold: true, align: 'right' })
      const trackX = this.M + 130
      const trackW = this.W - this.M - 40 - trackX
      this.doc.setFillColor(...LINE)
      this.doc.roundedRect(trackX, this.y + 2, trackW, 8, 4, 4, 'F')
      this.doc.setFillColor(...(color ?? RED))
      this.doc.roundedRect(trackX, this.y + 2, Math.max(3, (value / total) * trackW), 8, 4, 4, 'F')
      this.y += 18
    }
    this.y += 8
  }

  executiveSummary(data: ReportData) {
    this.newPage()
    this.sectionTitle('Executive Summary')
    this.kpiGrid([
      ['Total Customers', String(data.totals.customers)],
      ['Total Visits', String(data.totals.visits)],
      ['Total Photos', String(data.totals.photos)],
      ['Avg Visits / Customer', data.avgVisitsPerCustomer.toFixed(1)],
      ['Avg Photos / Visit', data.avgPhotosPerVisit.toFixed(1)],
      ['GPS Verified', String(data.totals.gpsVerified)],
      ['Latest Visit', safeDate(data.latestVisit, 'd MMM yyyy')],
      ['Oldest Visit', safeDate(data.oldestVisit, 'd MMM yyyy')],
      ['Cities', String(Object.keys(data.cityBreakdown).length)],
    ])
    this.y += 6

    this.bars(
      'Visit Status Breakdown',
      (['excellent', 'good', 'needs_follow_up', 'urgent'] as VisitStatus[])
        .filter((s) => data.statusBreakdown[s])
        .map((s) => [visitStatusLabel(s), data.statusBreakdown[s], STATUS_RGB[s]] as [string, number, [number, number, number]]),
    )
    this.bars(
      'Visit Type Breakdown',
      Object.entries(data.typeBreakdown)
        .sort((a, b) => b[1] - a[1])
        .map(([t, n]) => [visitTypeLabel(t as never), n] as [string, number]),
    )
    this.bars(
      'Category Breakdown',
      Object.entries(data.categoryBreakdown).sort((a, b) => b[1] - a[1]),
    )
    this.bars(
      'Cities',
      Object.entries(data.cityBreakdown).sort((a, b) => b[1] - a[1]).slice(0, 10),
    )
  }

  // ----------------------------------------------------------- customer page

  photoGroups(section: ReportCustomerSection): { label: string; paths: string[] }[] {
    const groups = new Map<string, string[]>()
    // Seed the "seen" set with the hero image so it is never repeated here, and
    // so no photo is ever shown twice across groups.
    const seen = new Set<string>(section.storefront ? [section.storefront.full] : [])
    const push = (label: string, path: string) => {
      if (!path || seen.has(path)) return
      seen.add(path)
      const arr = groups.get(label) ?? []
      arr.push(path)
      groups.set(label, arr)
    }
    // Additional store fronts only — those that differ from the hero image.
    for (const v of section.visits) {
      if (v.storefront_photo_url) push('Additional Store Fronts', v.storefront_photo_url)
    }
    for (const v of section.visits) {
      const label =
        v.visit_type === 'display_check' ? 'Display Photos'
        : v.visit_type === 'promotion' ? 'Promotion Photos'
        : v.visit_type === 'availability' ? 'Availability Photos'
        : v.visit_type === 'collection' ? 'Collection Photos'
        : 'Other Photos'
      for (const p of v.photos) push(label, p.storage_path)
    }
    const order = [
      'Additional Store Fronts',
      'Display Photos',
      'Promotion Photos',
      'Availability Photos',
      'Collection Photos',
      'Other Photos',
    ]
    // Cap total per customer, preserving group order.
    let budget = MAX_PHOTOS_PER_CUSTOMER
    const out: { label: string; paths: string[] }[] = []
    for (const label of order) {
      const paths = groups.get(label)
      if (!paths || budget <= 0) continue
      const take = paths.slice(0, budget)
      budget -= take.length
      out.push({ label, paths: take })
    }
    return out
  }

  photoGrid(paths: string[], cols = 3) {
    const gap = 8
    const cellW = (this.contentW - gap * (cols - 1)) / cols
    const cellH = cellW * 0.72
    for (let i = 0; i < paths.length; i++) {
      const col = i % cols
      if (col === 0) this.ensure(cellH + gap)
      const x = this.M + col * (cellW + gap)
      const rowY = this.y
      const img = this.images[paths[i]]
      this.doc.setFillColor(...SOFT)
      this.doc.roundedRect(x, rowY, cellW, cellH, 6, 6, 'F')
      if (img) {
        try {
          this.doc.addImage(img, 'JPEG', x, rowY, cellW, cellH, undefined, 'FAST')
        } catch {
          /* skip */
        }
      }
      if (col === cols - 1 || i === paths.length - 1) this.y += cellH + gap
    }
  }

  /** Estimated rendered height of a customer with the given hero/grid layout. */
  measureCustomer(
    section: ReportCustomerSection,
    groups: { label: string; paths: string[] }[],
    heroAspect: number,
    cols: number,
  ): number {
    const c = section.customer
    let h = 68 // header band + gap
    if (section.storefront) h += this.contentW * heroAspect + 14
    // Info rows
    let infoCount = 2 // Created + Last Visit are always present
    if (c.address) infoCount++
    if (c.city || c.area) infoCount++
    const hasCoords = c.latitude != null && c.longitude != null
    if (hasCoords) infoCount++
    h += infoCount * 18 + 6
    if (hasCoords) h += 22 // Google Maps link row
    // Timeline
    if (section.visits.length > 0) {
      h += 18
      for (const v of section.visits) h += 18 + (v.notes ? 3 : 2) * 12 + 6
      h += 4
    }
    // Photo groups
    const gap = 8
    const cellW = (this.contentW - gap * (cols - 1)) / cols
    const cellH = cellW * 0.72
    for (const g of groups) {
      const n = g.paths.length
      if (n === 0) continue
      h += 16 + Math.ceil(n / cols) * (cellH + gap) + 4
    }
    // Customer summary
    h += 90 + 10
    return h
  }

  customerSection(section: ReportCustomerSection, index: number) {
    this.newPage()
    const d = this.doc
    const c = section.customer

    // Photo groups (hero already excluded, deduplicated), image-filtered.
    const groups = this.photoGroups(section)
      .map((g) => ({ label: g.label, paths: g.paths.filter((p) => this.images[p]) }))
      .filter((g) => g.paths.length > 0)
    const totalPhotos = groups.reduce((s, g) => s + g.paths.length, 0)

    // Pick the least-compact layout that still keeps the whole customer on one
    // page. Progressively smaller hero + more photo columns are tried; the first
    // candidate that fits wins, otherwise the most compact one is used and the
    // content is allowed to flow onto a second page.
    const usable = this.H - this.M - 46
    const candidates: { heroAspect: number; cols: number }[] = [
      { heroAspect: 0.4, cols: totalPhotos > 6 ? 4 : 3 },
      { heroAspect: 0.34, cols: 4 },
      { heroAspect: 0.3, cols: 4 },
      { heroAspect: 0.28, cols: 5 },
    ]
    let plan = candidates[0]
    for (const cand of candidates) {
      plan = cand
      if (this.measureCustomer(section, groups, cand.heroAspect, cand.cols) <= usable) break
    }
    const { heroAspect, cols } = plan

    // Header band
    d.setFillColor(...RED)
    d.roundedRect(this.M, this.y, this.contentW, 52, 8, 8, 'F')
    this.text(`${index + 1}. ${c.name}`, this.M + 16, this.y + 25, { size: 15, bold: true, color: [255, 255, 255] })
    this.text(
      [categoryLabel(c), c.code].filter(Boolean).join(' · '),
      this.M + 16,
      this.y + 42,
      { size: 10, color: [255, 225, 226] },
    )
    this.text(`${section.totalVisits} visits`, this.W - this.M - 16, this.y + 30, { size: 12, bold: true, color: [255, 255, 255], align: 'right' })
    this.y += 68

    // Hero storefront — render the photo when available, otherwise a labelled
    // placeholder so the layout stays intact even if the image failed to load.
    if (section.storefront) {
      const heroH = this.contentW * heroAspect
      this.ensure(heroH + 12)
      const img = this.images[section.storefront.full]
      let drawn = false
      if (img) {
        try {
          this.doc.addImage(img, 'JPEG', this.M, this.y, this.contentW, heroH, undefined, 'FAST')
          drawn = true
        } catch {
          drawn = false
        }
      }
      if (!drawn) {
        d.setFillColor(...SOFT)
        d.roundedRect(this.M, this.y, this.contentW, heroH, 8, 8, 'F')
        this.text('Store Front Photo unavailable', this.W / 2, this.y + heroH / 2, { size: 10, color: MUTED, align: 'center' })
      }
      this.y += heroH + 14
    }

    // Info rows
    const info: [string, string][] = []
    if (c.address) info.push(['Address', c.address])
    if (c.city || c.area) info.push(['City', [c.city, c.area].filter(Boolean).join(' · ')])
    if (c.latitude != null && c.longitude != null) {
      info.push(['Coordinates', `${c.latitude.toFixed(5)}, ${c.longitude.toFixed(5)}`])
    }
    info.push(['Created', safeDate(c.created_at, 'd MMM yyyy')])
    info.push(['Last Visit', safeDate(section.lastVisit, 'd MMM yyyy')])
    for (const [label, value] of info) {
      this.ensure(20)
      this.text(label, this.M, this.y + 8, { size: 9, color: MUTED })
      this.text(value, this.M + 110, this.y + 8, { size: 9, bold: true })
      this.y += 18
    }
    if (c.latitude != null && c.longitude != null) {
      this.ensure(20)
      this.text('Google Maps', this.M, this.y + 8, { size: 9, color: MUTED })
      this.doc.setTextColor(0, 122, 255)
      this.doc.textWithLink('Open location', this.M + 110, this.y + 8, {
        url: googleMapsUrl(c.latitude, c.longitude),
      })
      this.y += 22
    }
    this.y += 6

    // Timeline
    if (section.visits.length > 0) {
      this.ensure(26)
      this.text('Visit Timeline', this.M, this.y + 6, { size: 12, bold: true })
      this.y += 18
      section.visits.forEach((v, i) => {
        const rows = v.notes ? 3 : 2
        this.ensure(20 + rows * 12)
        d.setFillColor(...SOFT)
        const boxH = 18 + rows * 12
        d.roundedRect(this.M, this.y, this.contentW, boxH, 6, 6, 'F')
        // status dot
        d.setFillColor(...STATUS_RGB[v.status as VisitStatus])
        d.circle(this.M + 14, this.y + 16, 4, 'F')
        this.text(
          `Visit ${section.visits.length - i} · ${safeDate(v.visited_at, 'd MMM yyyy · HH:mm')}`,
          this.M + 26,
          this.y + 19,
          { size: 9.5, bold: true },
        )
        this.text(
          `${visitTypeLabel(v.visit_type)} · ${visitStatusLabel(v.status)}`,
          this.W - this.M - 12,
          this.y + 19,
          { size: 9, color: MUTED, align: 'right' },
        )
        let ly = this.y + 33
        if (v.latitude != null && v.longitude != null) {
          this.text(`GPS ${v.latitude.toFixed(4)}, ${v.longitude.toFixed(4)}`, this.M + 26, ly, { size: 8.5, color: MUTED })
          ly += 12
        }
        if (v.notes) {
          const lines = this.doc.splitTextToSize(v.notes, this.contentW - 40) as string[]
          this.text(lines.slice(0, 2).join(' '), this.M + 26, ly, { size: 8.5, color: INK })
        }
        this.y += boxH + 6
      })
      this.y += 4
    }

    // Grouped photo galleries — hero excluded, no duplicates, compact grid.
    for (const group of groups) {
      this.ensure(24)
      this.text(group.label, this.M, this.y + 6, { size: 11, bold: true })
      this.y += 16
      this.photoGrid(group.paths, cols)
      this.y += 4
    }

    // Customer summary
    this.ensure(96)
    d.setFillColor(...SOFT)
    const sh = 90
    d.roundedRect(this.M, this.y, this.contentW, sh, 8, 8, 'F')
    this.text('Customer Summary', this.M + 14, this.y + 20, { size: 11, bold: true })
    const sumRows: [string, string][] = [
      ['Total Visits', String(section.totalVisits)],
      ['First Visit', safeDate(section.firstVisit, 'd MMM yyyy')],
      ['Last Visit', safeDate(section.lastVisit, 'd MMM yyyy')],
      ['Avg Frequency', section.avgFrequencyDays != null ? `${section.avgFrequencyDays.toFixed(1)} days` : '—'],
      ['Latest Status', section.latestStatus ? visitStatusLabel(section.latestStatus) : '—'],
      ['Follow-up Needed', section.followUpNeeded ? 'Yes' : 'No'],
    ]
    sumRows.forEach((r, i) => {
      const col = i % 3
      const row = Math.floor(i / 3)
      const x = this.M + 14 + col * ((this.contentW - 28) / 3)
      const ry = this.y + 42 + row * 22
      this.text(r[0], x, ry, { size: 8.5, color: MUTED })
      this.text(r[1], x, ry + 13, { size: 10, bold: true })
    })
    this.y += sh + 10
  }

  finalSummary(data: ReportData) {
    this.newPage()
    this.sectionTitle('Final Report Summary')
    this.kpiGrid([
      ['Customers', String(data.totals.customers)],
      ['Visits', String(data.totals.visits)],
      ['Photos', String(data.totals.photos)],
    ])
    this.y += 6
    this.bars('Category Distribution', Object.entries(data.categoryBreakdown).sort((a, b) => b[1] - a[1]))
    this.bars(
      'Visit Status Distribution',
      (['excellent', 'good', 'needs_follow_up', 'urgent'] as VisitStatus[])
        .filter((s) => data.statusBreakdown[s])
        .map((s) => [visitStatusLabel(s), data.statusBreakdown[s], STATUS_RGB[s]] as [string, number, [number, number, number]]),
    )
    this.bars(
      'Visit Type Distribution',
      Object.entries(data.typeBreakdown).sort((a, b) => b[1] - a[1]).map(([t, n]) => [visitTypeLabel(t as never), n] as [string, number]),
    )
    this.ensure(30)
    this.text(
      `Generated ${format(new Date(data.generatedAt), 'd MMMM yyyy, HH:mm')} · ${data.reportId}`,
      this.M,
      this.y + 10,
      { size: 9, color: MUTED },
    )
  }

  footers() {
    const pages = this.doc.getNumberOfPages()
    for (let i = 1; i <= pages; i++) {
      this.doc.setPage(i)
      if (i === 1) continue // cover has its own footline
      this.doc.setDrawColor(...LINE)
      this.doc.line(this.M, this.H - 40, this.W - this.M, this.H - 40)
      this.text('Roshen Visit Log', this.M, this.H - 26, { size: 8, color: MUTED })
      this.text(`Page ${i} of ${pages}`, this.W - this.M, this.H - 26, { size: 8, color: MUTED, align: 'right' })
    }
  }
}

export interface ReportPdf {
  blob: Blob
  filename: string
}

/** Renders a full executive report to a PDF blob. */
export async function generateReportPdf(
  data: ReportData,
  onProgress?: (phase: string, done: number, total: number) => void,
): Promise<ReportPdf> {
  // Collect the photo paths we will actually render (respecting per-customer caps).
  const paths: string[] = []
  for (const section of data.customers) {
    if (section.storefront) paths.push(section.storefront.full)
    let budget = MAX_PHOTOS_PER_CUSTOMER
    for (const v of section.visits) {
      if (v.storefront_photo_url) paths.push(v.storefront_photo_url)
      for (const p of v.photos) {
        if (budget-- <= 0) break
        paths.push(p.storage_path)
      }
    }
  }
  const images = await loadReportImages(paths, (done, total) => onProgress?.('Loading photos', done, total))

  const report = new Report(images)
  report.cover(data)
  if (data.customers.length > 0 || data.totals.visits > 0) report.executiveSummary(data)
  data.customers.forEach((section, i) => {
    // Isolate each customer page: a single malformed record must never abort
    // the whole report.
    try {
      report.customerSection(section, i)
    } catch (error) {
      console.error('[report] customer section failed', section.customer?.id, error)
    }
    onProgress?.('Rendering customers', i + 1, data.customers.length)
  })
  report.finalSummary(data)
  report.footers()

  const scopeName =
    data.scope.type === 'single_customer' && data.customers[0]
      ? data.customers[0].customer.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')
      : data.scope.type
  const filename = `roshen-report-${scopeName}-${format(new Date(data.generatedAt), 'yyyyMMdd-HHmm')}.pdf`
  return { blob: report.doc.output('blob'), filename }
}
